services:

  traefik:
    image: traefik:v3.1
    container_name: traefik
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/traefik.yml:/traefik.yml:ro
      - ./traefik/acme.json:/acme.json
    command:
      - "--api=true"                 # включаем Dashboard
      - "--api.dashboard=true"       # explicit Dashboard
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.web.http.redirections.entryPoint.permanent=true"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.3nity.space`)"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.tls=true"
      - "traefik.http.routers.traefik.tls.certresolver=letsEncrypt"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.middlewares.traefik-auth.basicauth.users=admin:$$apr1$$wLGkE25P$$quD8O/Dse456ikobVYqhf0"
      - "traefik.http.routers.traefik.middlewares=traefik-auth"

        # глобальный Router для всех HTTP запросов
      - "traefik.http.routers.http-catchall.rule=HostRegexp(`{host:.+}`)"
      - "traefik.http.routers.http-catchall.entrypoints=web"
      - "traefik.http.routers.http-catchall.middlewares=redirect-to-https"

      # middleware redirect
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.permanent=true"
    networks:
      - default

  mongo:
    image: mongo:7.0
    container_name: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=trinity
      - MONGO_INITDB_ROOT_PASSWORD=Z8jGw190M
    ports:
      - 27017:27017
    volumes:
      - ./mongo-data-7.0:/data/db
    networks:
      - default

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3101:3000"
    networks:
      - default

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    networks:
      - default

  loki:
    image: grafana/loki:2.8.0
    ports:
      - "3100:3100"
    networks:
      - default

  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    env_file:
      - ./apps/backend/envs/.${ENVIRONMENT:-test}.env
    depends_on:
      - mongo
    expose:
      - "3000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`api.3nity.space`)"
      - "traefik.http.routers.backend.entrypoints=websecure"
      - "traefik.http.services.backend.loadbalancer.server.port=3000"
      - "traefik.http.routers.backend.tls.certresolver=letsEncrypt"
    networks:
      - default

  bot:
    build:
      context: .
      dockerfile: apps/bot/Dockerfile
    env_file:
      - ./apps/bot/envs/.${ENVIRONMENT:-test}.env
    depends_on:
      - mongo
    ports:
      - "3001:3001"
    networks:
      - default

  frontend:
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
    env_file:
      - ./apps/frontend/envs/.${ENVIRONMENT:-test}.env
    expose:
      - "4200"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`app.3nity.space`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.services.frontend.loadbalancer.server.port=4200"
      - "traefik.http.routers.frontend.tls.certresolver=letsEncrypt"

    networks:
      - default

  admin:
    build:
      context: .
      dockerfile: apps/admin/Dockerfile
    env_file:
      - ./apps/admin/envs/.${ENVIRONMENT:-test}.env
    expose:
      - "4201"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.admin.rule=Host(`admin.3nity.space`)"
      - "traefik.http.routers.admin.entrypoints=websecure"
      - "traefik.http.services.admin.loadbalancer.server.port=4201"
      - "traefik.http.routers.admin.tls.certresolver=letsEncrypt"
    networks:
      - default

volumes:
  mongo-data:

networks:
  default:
    driver: bridge
