services:
  test_grafana:
    image: grafana/grafana:latest
    ports:
      - "3111:3000"
    networks:
      - proxy

  test_prometheus:
    image: prom/prometheus:latest
    ports:
      - "9091:9090"
    networks:
      - proxy

  test_loki:
    image: grafana/loki:2.8.0
    ports:
      - "3110:3100"
    networks:
      - proxy

  test_backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    env_file:
      - ./apps/backend/envs/.env.test
    expose:
      - "3010"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.test-backend.rule=Host(`api.test.3nity.space`)"
      - "traefik.http.routers.test-backend.entrypoints=websecure"
      - "traefik.http.services.test-backend.loadbalancer.server.port=3010"
      - "traefik.http.routers.test-backend.tls.certresolver=letsEncrypt"
      - "traefik.http.routers.test-backend.tls=true"
    networks:
      - proxy

  test_bot:
    build:
      context: .
      dockerfile: apps/bot/Dockerfile
    env_file:
      - ./apps/bot/envs/.env.test
    ports:
      - "3011:3001"
    # labels:
    #   - "traefik.enable=true"
    #   - "traefik.http.routers.backend.rule=Host(`bot.test.3nity.space`)"
    #   - "traefik.http.routers.backend.entrypoints=websecure"
    #   - "traefik.http.services.backend.loadbalancer.server.port=3001"
    #   - "traefik.http.routers.backend.tls.certresolver=letsEncrypt"
    #   - "traefik.http.routers.backend.tls=true"
    networks:
      - proxy

  test_frontend:
    build:
      context: .
      dockerfile: apps/webapp/Dockerfile
    env_file:
      - apps/webapp/envs/.env.test
    ports:
      - "4213:4203"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.test-frontend.rule=Host(`app.test.3nity.space`)"
      - "traefik.http.routers.test-frontend.entrypoints=websecure"
      - "traefik.http.services.test-frontend.loadbalancer.server.port=4203"
      - "traefik.http.routers.test-frontend.tls.certresolver=letsEncrypt"
      - "traefik.http.routers.test-frontend.tls=true"
    networks:
      - proxy

  test_admin:
    build:
      context: .
      dockerfile: apps/admin/Dockerfile
    env_file:
      - ./apps/admin/envs/.env.test
    ports:
      - "4211:4201"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.test-admin.rule=Host(`admin.test.3nity.space`)"
      - "traefik.http.routers.test-admin.entrypoints=websecure"
      - "traefik.http.services.test-admin.loadbalancer.server.port=4201"
      - "traefik.http.routers.test-admin.tls.certresolver=letsEncrypt"
      - "traefik.http.routers.test-admin.tls=true"
    networks:
      - proxy

networks:
  proxy:
    external: true
