services:

  traefik:
    image: traefik:v3.1
    container_name: traefik
    restart: always
    command:
      - "--api.insecure=true"               # включаем дашборд
      - "--providers.docker=true"           # читаем конфигурацию из docker labels
      - "--entrypoints.web.address=:80"     # HTTP
    ports:
      - "80:80"      # HTTP для пользователей
      - "8080:8080"  # дашборд Traefik
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - default

  mongo:
    image: mongo:7.0
    container_name: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=trinity
      - MONGO_INITDB_ROOT_PASSWORD=Z8jGw190M
    ports:
      - 27017:27017
    volumes:
      - ./mongo-data-7.0:/data/db
    networks:
      - default

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3101:3000"
    networks:
      - default

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    networks:
      - default

  loki:
    image: grafana/loki:2.8.0
    ports:
      - "3100:3100"
    networks:
      - default

  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    env_file:
      - ./apps/backend/envs/.${ENVIRONMENT:-test}.env
    depends_on:
      - mongo
    expose:
      - "3000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`api.3nity.space`)"
      - "traefik.http.routers.backend.entrypoints=web"
      - "traefik.http.services.backend.loadbalancer.server.port=3000"
    networks:
      - default

  bot:
    build:
      context: .
      dockerfile: apps/bot/Dockerfile
    env_file:
      - ./apps/bot/envs/.${ENVIRONMENT:-test}.env
    depends_on:
      - mongo
    ports:
      - "3001:3001"
    networks:
      - default

  frontend:
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
    env_file:
      - ./apps/frontend/envs/.${ENVIRONMENT:-test}.env
    expose:
      - "4200"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`app.3nity.space`)"
      - "traefik.http.routers.frontend.entrypoints=web"
      - "traefik.http.services.frontend.loadbalancer.server.port=4200"

    networks:
      - default

  admin:
    build:
      context: .
      dockerfile: apps/admin/Dockerfile
    env_file:
      - ./apps/admin/envs/.${ENVIRONMENT:-test}.env
    expose:
      - "4201"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.admin.rule=Host(`admin.3nity.space`)"
      - "traefik.http.routers.admin.entrypoints=web"
      - "traefik.http.services.admin.loadbalancer.server.port=4201"
    networks:
      - default

volumes:
  mongo-data:

networks:
  default:
    driver: bridge
