services:
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3101:3000"
    networks:
      - default
    depends_on:
      loki:
        condition: service_healthy

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    networks:
      - default

  loki:
    image: grafana/loki:2.8.0
    ports:
      - "3100:3100"
    networks:
      - default
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3100/ready"]
      interval: 10s
      retries: 5


networks:
  default:
    driver: bridge
