# traefik.yml
api:
  dashboard: true       # включаем дашборд

log:
  level: INFO

entryPoints:
  web:
    address: ":80"      # HTTP

providers:
  docker:
    exposedByDefault: false  # по умолчанию Traefik не будет проксировать все контейнеры, только те, где явно указаны labels
